matrix:
  VERSION:
    - "4.3.1"

publish:
  docker:
    file: "$$VERSION/Dockerfile"
    context: "$$VERSION"
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/kibana
    tag: "$$VERSION"
    force_tag: true
    storage_driver: overlay
